### ISSUE TITLE
required-fields rule causes ESLint crash when referencing non-existent field

### ISSUE THREAD

**Issue by benjie** [apollographql/eslint-plugin-graphql#63]
When running `eslint` against code that has a bad field reference (`nx` does not exist):

```js
// ...

const query = gql`
query Blah {
  thing {
    foo
    bar
    nx
  }
}
`;
```

Intended outcome: "field nx does not exist"

Actual outcome: 

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at .../node_modules/eslint-plugin-graphql/lib/rules.js:28:39
    at Array.forEach (native)
    at Object.Field (.../node_modules/eslint-plugin-graphql/lib/rules.js:27:22)
    at Object.enter (.../node_modules/graphql/language/visitor.js:297:29)
    at Object.enter (.../node_modules/graphql/language/visitor.js:339:25)
    at visit (.../node_modules/graphql/language/visitor.js:229:26)
    at visitUsingRules (.../node_modules/graphql/validation/validate.js:77:22)
    at validate (.../node_modules/graphql/validation/validate.js:62:10)
    at handleTemplateTag (.../node_modules/eslint-plugin-graphql/lib/index.js:353:57)
    at EventEmitter.TaggedTemplateExpression (.../node_modules/eslint-plugin-graphql/lib/index.js:112:20)
```

I believe something like this should fix it: https://github.com/benjie/eslint-plugin-graphql/commit/0d6214d99805e1233cfce41924791befa961ae26

(In fact I just went in and edited the file in node_modules and that does indeed fix the issue.)

ESLint rules snippet:

```js
    "graphql/template-strings": [
      "error",
      {
        env: "apollo",
        schemaJson: require("./data/schema.json"),
      },
    ],
    "graphql/required-fields": [
      "error",
      {
        schemaJson: require("./data/schema.json"),
        requiredFields: ["__typename", "id"],
      },
    ],
```

**Comment by jnwng** [comment]
@benjie would definitely accept a PR to fix this — having a test or two would be swell, too!

**Comment by benjie** [comment]
Reproduced in your test suite 👍 

PR to follow
