### ISSUE TITLE
"required-fields" rule crash for InlineFragment

### ISSUE THREAD

**Issue by leethree** [apollographql/eslint-plugin-graphql#79]
Eslint crashes when there's a required field along with an inline fragment.

Eslint config:
```json
"graphql/required-fields": ["error", {
      "requiredFields": ["id"],
      "schemaJsonFilepath": "./data/schema.json"
    }]
```

Schema:
```
interface Viewer {
  id: ID!
}
type UserViewer implements Viewer {
  id: ID!
  firstName: String
  lastName: String
}
```

Query:
```graphql
{
  viewer {
    ... on UserViewer {
       firstName
    }
  }
}
```

Intended:
```
error  'id' field required on 'viewer'
```

Actual:
```
Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
    at /[...]/node_modules/eslint-plugin-graphql/lib/rules.js:44:26
    at Array.find (native)
    at /[...]/node_modules/eslint-plugin-graphql/lib/rules.js:42:66
[...]
```

**Comment by cspeper** [comment]
Any update on this issue? I'm seeing this as well.
